name: deploy to live

on:
  push:
    branches: 
      - live

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/build

      - uses: ./.github/actions/ssh
        with:
          ssh-host: "lthelectronics.ssh.wpengine.net"
          ssh-private-key: "${{ secrets.SSH_PRIVATE_KEY }}"
        
      - name: copy files
        if: github.ref == 'refs/heads/live'
        run: |
          rsync -mrchivz --times --omit-dir-times --delete-after \
          ./httpdocs/wp-content/themes/clearing \
          lthelectronics@lthelectronics.ssh.wpengine.net:sites/lthelectronics/wp-content/themes